[package]
name = "rust-extensions"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
objects-pool = []
base64 = ["dep:base64"]
with-tokio = ["tokio", "signal-hook"]

[dependencies]
tokio = { version = "*", features = ["full"], optional = true }
chrono = "*"
async-trait = "*"
signal-hook = { version = "*", optional = true }
base64 = { version = "*", optional = true }
serde = { version = "*", features = ["derive"] }


[dev-dependencies]
serde_json = "*"
