[package]
name = "rust-extensions"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
objects-pool = []
base64 = ["dep:base64"]

[dependencies]
tokio = { version = "*", features = ["full"] }
chrono = "*"
async-trait = "*"
signal-hook = "*"
base64 = { version = "*", optional = true }
serde = { version = "*", features = ["derive"] }


[dev-dependencies]
serde_json = "*"
