[package]
name = "rust-extensions"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
objects-pool = []

[dependencies]
tokio = { version = "*", features = ["full"] }
chrono = "*"
async-trait = "*"
signal-hook = "*"
